### ISSUE TITLE
Добавить поддержку doiuse

### ISSUE THREAD

**Issue by webrune** [yunusga/marmelad#38]
Очень классный и полезный плагин, позволяет просто указать поддерживаемые браузеры и если написать что-то, что не поддерживается одним из этих браузеров, покажет предупреждение.

https://github.com/anandthakker/doiuse

**Comment by yunusga** [comment]
Планировал добавить ещё stylint. Хотя сейчас проблем с поддержкой вроде как нет. Подумаем над эти до нового года
